fastlane_version "2.64.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Marvel")
    slather(
      output_directory: "coverage",
      workspace: "Marvel.xcworkspace",
      scheme: "Marvel",
      proj: "Marvel.xcodeproj",
      html: true
    )
  end
end
